CREATE DATABASE BD_ACADEMIA;

USE BD_ACADEMIA;

CREATE TABLE PROFESSOR(
	IDPROFESSOR		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOME			VARCHAR(50) NOT NULL,
	CPF				CHAR(11) NOT NULL, --UNIQUE
	IDADE			INT NOT NULL,
	CELULAR			CHAR(11) NOT NULL,
	EMAIL			VARCHAR(50) NOT NULL,	
	USUARIO			VARCHAR(30) NOT NULL,
	SENHA			VARCHAR(30) NOT NULL,

	RUA				VARCHAR(100) NOT NULL,
	NUMERO			INT NOT NULL,
	APTO			VARCHAR(5),
	BAIRRO			VARCHAR(50) NOT NULL,
	CIDADE			VARCHAR(50) NOT NULL,
	ESTADO			CHAR(2) NOT NULL
);

CREATE TABLE ALUNO(
	IDALUNO		INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOME			VARCHAR(50) NOT NULL,
	CPF				CHAR(11) NOT NULL, --UNIQUE
	IDADE			INT NOT NULL,
	CELULAR			CHAR(11) NOT NULL,
	EMAIL			VARCHAR(50) NOT NULL,
	USUARIO			VARCHAR(30) NOT NULL,
	SENHA			VARCHAR(30) NOT NULL,
	PESO			INT,
	ALTURA			INT,

	RUA				VARCHAR(100) NOT NULL,
	NUMERO			INT NOT NULL,
	APTO			VARCHAR(5),
	BAIRRO			VARCHAR(50) NOT NULL,
	CIDADE			VARCHAR(50) NOT NULL,
	ESTADO			CHAR(2) NOT NULL
);

CREATE TABLE AULA(
	IDAULA			INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	NOME			VARCHAR(50) NOT NULL,
	DIA				DATE NOT NULL,
	HORA			CHAR(3) NOT NULL,
	TOTAL			INT,
	ID_PROFESSOR	INT,

	FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR(IDPROFESSOR)
);

CREATE TABLE PARTICIPANTE(
	IDPARTICIPANTE	INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	ID_AULA			INT NOT NULL,
	ID_ALUNO		INT NOT NULL,

	FOREIGN KEY (ID_AULA) REFERENCES AULA(IDAULA),
	FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(IDALUNO)
);

SELECT * FROM PROFESSOR;
SELECT * FROM ALUNO;
SELECT * FROM AULA;
SELECT * FROM PARTICIPANTE;

--drop table participante
--drop table aula
--drop table aluno
--drop table professor

/*
INSERT INTO ALUNO (NOME, CPF, IDADE, CELULAR, EMAIL, USUARIO, SENHA, PESO, ALTURA, RUA, NUMERO, BAIRRO, CIDADE, ESTADO)
VALUES ('Henrique Menezes', '12345678912', 19, '11222223333', 'henrique@gmail.com', 'henrique-mo', '321654', 65, 178, 'Avenida da Moda', 123, 'Centro', 'Passos', 'MG');

INSERT INTO PROFESSOR (NOME, CPF, IDADE, CELULAR, EMAIL, USUARIO, SENHA, RUA, NUMERO, BAIRRO, CIDADE, ESTADO)
VALUES ('João da Silva', '32165498732', 23, '12123451234', 'joao@gmail.com', 'joao-ds', '321654', 'Antônio Carlos', 321, 'Centro', 'Passos', 'MG');

INSERT INTO AULA (NOME, DIA, HORA, ID_PROFESSOR)
VALUES ('Judô', '2022-11-09', '07h', 1);

INSERT INTO PARTICIPANTE (ID_AULA, ID_ALUNO)
VALUES (1, 1);

*/

SELECT * FROM PROFESSOR;
SELECT * FROM ALUNO;
SELECT * FROM AULA;
SELECT * FROM PARTICIPANTE;

SELECT AULA.NOME AS 'Aula', AULA.DIA AS 'Dia', AULA.HORA AS 'Horário', ALUNO.NOME AS 'Aluno', PROFESSOR.NOME AS 'Professor' 
FROM PARTICIPANTE
LEFT JOIN AULA ON AULA.IDAULA = PARTICIPANTE.ID_AULA
LEFT JOIN ALUNO ON ALUNO.IDALUNO = PARTICIPANTE.ID_ALUNO
LEFT JOIN PROFESSOR ON PROFESSOR.IDPROFESSOR = AULA.ID_PROFESSOR
ORDER BY AULA.NOME;


--SELECT ALUNO.NOME, ALUNO.CPF FROM ALUNO JOIN PARTICIPANTE ON PARTICIPANTE.ID_ALUNO = ALUNO.IDALUNO WHERE PARTICIPANTE.ID_AULA = 1;
--SELECT PROFESSOR.NOME, PROFESSOR.CPF FROM PROFESSOR JOIN AULA ON AULA.ID_PROFESSOR = PROFESSOR.IDPROFESSOR JOIN PARTICIPANTE ON AULA.IDAULA = PARTICIPANTE.ID_AULA WHERE PARTICIPANTE.ID_AULA = 1;

--FILTRAR AULAS POR ID DO ALUNO
CREATE PROCEDURE P_FILTRAR_AULAS 
@ID INT AS
BEGIN
	SELECT AULA.IDAULA AS 'ID', AULA.NOME AS 'Aula', PROFESSOR.NOME AS 'Professor', AULA.DIA AS 'Data', AULA.HORA AS 'Horário'
	FROM AULA INNER JOIN PARTICIPANTE ON PARTICIPANTE.ID_AULA = AULA.IDAULA
	INNER JOIN PROFESSOR ON PROFESSOR.IDPROFESSOR = AULA.ID_PROFESSOR
	WHERE PARTICIPANTE.ID_ALUNO = @ID;
END
